//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace DevConnect
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body_load_image_account_upload_image_post
    {
        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public byte[] Image { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body_load_image_post_upload_image__post_id__post
    {
        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public byte[] Image { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body_login_for_access_token_auth_token_post
    {
        
        [System.ComponentModel.DataAnnotations.RegularExpression(@"password")]
        public string Grant_type { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Password { get; set; } = default!;

        
        public string Scope { get; set; } = "";

        
        public string Client_id { get; set; } = default!;

        
        public string Client_secret { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body_upload_image_community_upload_image__community_id__post
    {
        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public byte[] Image { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CommentCreateSchema
    {
        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Text { get; set; } = default!;

        
        public int AuthorId { get; set; } = default!;

        
        public int PostId { get; set; } = default!;

        
        public int CommentId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CommentReadSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Text { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSmallSchema Author { get; set; } = new UserReadSmallSchema();

        
        public int PostId { get; set; } = default!;

        
        public int CommentId { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        
        public System.DateTimeOffset UpdatedAt { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CommentReadWithChildSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Text { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSmallSchema Author { get; set; } = new UserReadSmallSchema();

        
        public int PostId { get; set; } = default!;

        
        public int CommentId { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        
        public System.DateTimeOffset UpdatedAt { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.List<CommentReadSchema> Comments { get; set; } = new System.Collections.Generic.List<CommentReadSchema>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CommentUpdateSchema
    {
        
        public string Text { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CommunityCreateSchema
    {
        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; } = default!;

        
        public System.Collections.Generic.List<CommunityThemes> Themes { get; set; } = default!;

        
        public System.Collections.Generic.List<string> Tags { get; set; } = default!;

        
        public string Description { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CommunityReadSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSchemaShort Admin { get; set; } = new UserReadSchemaShort();

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; } = default!;

        
        public System.Collections.Generic.List<CommunityThemes> Themes { get; set; } = default!;

        
        public System.Collections.Generic.List<string> Tags { get; set; } = default!;

        
        public string BannerUrl { get; set; } = default!;

        
        public string AvatarUrl { get; set; } = default!;

        
        public string Description { get; set; } = default!;

        
        public int SubscribersAmount { get; set; } = 0;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        
        public bool IsJoined { get; set; } = false;

        
        public System.Collections.Generic.List<Application__community__schemas__PostReadSchema> Posts { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum CommunityThemes
    {

        [System.Runtime.Serialization.EnumMember(Value = @"PROGRAMMING")]
        PROGRAMMING = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"TECHNOLOGY")]
        TECHNOLOGY = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"EDUCATION")]
        EDUCATION = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"SPORT")]
        SPORT = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"OTHER")]
        OTHER = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CommunityUpdateSchema
    {
        
        public string Name { get; set; } = default!;

        
        public System.Collections.Generic.List<CommunityThemes> Themes { get; set; } = default!;

        
        public System.Collections.Generic.List<string> Tags { get; set; } = default!;

        
        public string Description { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HTTPValidationError
    {
        
        public System.Collections.Generic.List<ValidationError> Detail { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ImageType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"BANNER")]
        BANNER = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"AVATAR")]
        AVATAR = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MessageReadSchema
    {
        
        public int Id { get; set; } = default!;

        
        public int UserFromId { get; set; } = default!;

        
        public int PersonalChatId { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Text { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        
        public bool IsRead { get; set; } = default!;

        
        public System.DateTimeOffset UpdatedAt { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Page_CommunityShortReadSchema_
    {
        
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.List<Application__community__schemas__CommunityShortReadSchema> Items { get; set; } = new System.Collections.Generic.List<Application__community__schemas__CommunityShortReadSchema>();

        
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Total { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int Page { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int Size { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Pages { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Page_PostReadSchema_
    {
        
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.List<Application__community__schemas__PostReadSchema> Items { get; set; } = new System.Collections.Generic.List<Application__community__schemas__PostReadSchema>();

        
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Total { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int Page { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int Size { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Pages { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Page_UserReadSchemaShort_
    {
        
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.List<UserReadSchemaShort> Items { get; set; } = new System.Collections.Generic.List<UserReadSchemaShort>();

        
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Total { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int Page { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int Size { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Pages { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PersonalChatReadSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSchemaShort UserFirst { get; set; } = new UserReadSchemaShort();

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSchemaShort UserSecond { get; set; } = new UserReadSchemaShort();

        
        public System.Collections.Generic.List<MessageReadSchema> Messages { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PersonalChatReadShortSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSchemaShort UserFrom { get; set; } = new UserReadSchemaShort();

        
        public string Message { get; set; } = default!;

        
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        
        public int UnreadMessages { get; set; } = 0;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PostCreateSchema
    {
        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; } = default!;

        
        public string Content { get; set; } = default!;

        
        public int AuthorId { get; set; } = default!;

        
        public int CommunityId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PostUpdateSchema
    {
        
        public string Title { get; set; } = default!;

        
        public string Content { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RefreshToken
    {
        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Refresh_token { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Token
    {
        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Access_token { get; set; } = default!;

        
        public string Refresh_token { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Token_type { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UserReadSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; } = default!;

        
        public string AvatarUrl { get; set; } = default!;

        
        public int SubscribersAmount { get; set; } = 0;

        
        public string FirstName { get; set; } = "";

        
        public string LastName { get; set; } = "";

        
        public bool IsActive { get; set; } = default!;

        
        public System.Collections.Generic.List<string> Stack { get; set; } = default!;

        
        public string City { get; set; } = "";

        
        public string Description { get; set; } = "";

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UserReadSchemaShort
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; } = default!;

        
        public string AvatarUrl { get; set; } = default!;

        
        public int SubscribersAmount { get; set; } = 0;

        
        public string FirstName { get; set; } = "";

        
        public string LastName { get; set; } = "";

        
        public bool IsActive { get; set; } = default!;

        
        public System.Collections.Generic.List<string> Stack { get; set; } = default!;

        
        public string City { get; set; } = "";

        
        public string Description { get; set; } = "";

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UserReadSmallSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; } = default!;

        
        public string AvatarUrl { get; set; } = default!;

        
        public int SubscribersAmount { get; set; } = 0;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UserUpdateSchema
    {
        
        public string FirstName { get; set; } = default!;

        
        public string LastName { get; set; } = default!;

        
        public System.Collections.Generic.List<string> Stack { get; set; } = default!;

        
        public string City { get; set; } = default!;

        
        public string Description { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ValidationError
    {
        
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.List<string> Loc { get; set; } = new System.Collections.Generic.List<string>();

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Msg { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Application__community__schemas__CommunityShortReadSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSchemaShort Admin { get; set; } = new UserReadSchemaShort();

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; } = default!;

        
        public System.Collections.Generic.List<CommunityThemes> Themes { get; set; } = default!;

        
        public System.Collections.Generic.List<string> Tags { get; set; } = default!;

        
        public string BannerUrl { get; set; } = default!;

        
        public string AvatarUrl { get; set; } = default!;

        
        public string Description { get; set; } = default!;

        
        public int SubscribersAmount { get; set; } = 0;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        
        public bool IsJoined { get; set; } = false;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Application__community__schemas__PostReadSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; } = default!;

        
        public int CommunityId { get; set; } = default!;

        
        public string Content { get; set; } = "";

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSchemaShort Author { get; set; } = new UserReadSchemaShort();

        
        public System.Collections.Generic.List<string> Images { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        
        public System.DateTimeOffset UpdatedAt { get; set; } = default!;

        
        public int Likes { get; set; } = default!;

        
        public System.Collections.Generic.List<CommentReadWithChildSchema> Comments { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Application__post__schemas__CommunityShortReadSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSchemaShort Admin { get; set; } = new UserReadSchemaShort();

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; } = default!;

        
        public object Themes { get; set; } = default!;

        
        public System.Collections.Generic.List<string> Tags { get; set; } = default!;

        
        public string BannerUrl { get; set; } = default!;

        
        public string AvatarUrl { get; set; } = default!;

        
        public string Description { get; set; } = default!;

        
        public int SubscribersAmount { get; set; } = 0;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Application__post__schemas__PostReadSchema
    {
        
        public int Id { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; } = default!;

        
        public int CommunityId { get; set; } = default!;

        
        public string Content { get; set; } = "";

        
        [System.ComponentModel.DataAnnotations.Required]
        public UserReadSchemaShort Author { get; set; } = new UserReadSchemaShort();

        
        public System.Collections.Generic.List<string> Images { get; set; } = default!;

        
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        
        public System.DateTimeOffset UpdatedAt { get; set; } = default!;

        
        public int Likes { get; set; } = default!;

        
        public System.Collections.Generic.List<CommentReadWithChildSchema> Comments { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FileParameter
    {
        public FileParameter(System.IO.Stream data)
            : this (data, null, null)
        {
        }

        public FileParameter(System.IO.Stream data, string? fileName)
            : this (data, fileName, null)
        {
        }

        public FileParameter(System.IO.Stream data, string? fileName, string? contentType)
        {
            Data = data;
            FileName = fileName;
            ContentType = contentType;
        }

        public System.IO.Stream Data { get; private set; }

        public string? FileName { get; private set; }

        public string? ContentType { get; private set; }
    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625